- name: VPN
  hosts: all
  become: yes
  tasks:

  - name: fix repos
    shell: cd /etc/yum.repos.d/ && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    when: ansible_os_family == "RedHat"

# Включим проброс пакетов на всех хостах
  - name: allow forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes

# Установим epel репозиторий:
  - name: install epel
    dnf:
      name: 
        - epel-release
      state: present
      update_cache: yes

# Установим openvpn и iperf3:
  - name: install openvpn & iperf3
    dnf:
      name: 
        - openvpn
        - iperf3       
      state: present
      update_cache: yes

# Выключим SELinux
  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled

# Cоздаём файл-ключ на сервере
  - name: Create /etc/openvpn/static.key
    shell: openvpn --genkey --secret /etc/openvpn/static.key
    when: ansible_hostname == "server"    

# Скопируем server.conf и unit-файл на сервер
  - name: Copy server.conf & unit-file
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - { src: "templates/server.conf_server", dest: "/etc/openvpn/server.conf", mode: "0644"}
      - { src: "templates/openvpn@.service", dest: "/etc/systemd/system/openvpn@.service", mode: "0644"}
    when: ansible_hostname == "server" 

# Заберём файл-ключ с сервера
  - name: fetch key
    fetch:
      src: /etc/openvpn/static.key
      dest: ./static.key
    when: ansible_hostname == "server" 

# Скопируем server.conf и файл-ключ на клиент
  - name: copy key & config & unit сервиса openvpn
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - { src: "templates/server.conf_client", dest: "/etc/openvpn/server.conf", mode: "0644"}
      - { src: "static.key/server/etc/openvpn/static.key", dest: "/etc/openvpn/static.key", mode: "0644"}
      - { src: "templates/openvpn@.service", dest: "/etc/systemd/system/openvpn@.service", mode: "0644"}
    when: ansible_hostname == "client" 


# Включим openvpn@server на сервер
  - name: start and enable openvpn@server
    systemd:
      name: openvpn@server
      state: started
      enabled: yes

